services:
  cyclops:
    container_name: cyclops
    image: cyclopsimg
    env_file:
      - '.env'
    build: ./srcs/backend
    init: true
    networks:
      - netone
    volumes:
      #For Project
      - ./srcs/backend/core/core:/cyclops/core
      - ./srcs/backend/core/wallet:/cyclops/wallet

  nginx:
    container_name: nginx
    build: ./srcs/nginx
    image: nginximg
    ports:
      - '22222:80'
    depends_on:
      - cyclops
      - frontend
    init: true
    networks:
      - netone
    env_file:
      - '.env'
  frontend:
    container_name: frontend
    image: frontendimg
    build: ./srcs/frontend
    ports:
      - '5173:5173'
    init: true
    networks:
      - netone
    env_file:
      - '.env'
      
    volumes:
      - ./srcs/frontend:/app
      - /app/node_modules
networks:
  netone:
    name: the_network
