# Generated by Django 6.0.4 on 2026-04-18 12:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('provider', models.CharField(choices=[('IAM', 'IAM'), ('INWI', 'INWI'), ('ORANGE', 'Orange')], default='IAM', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=20)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='MAR', max_length=10)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('family_status', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('average_income', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_type', models.CharField(blank=True, default='', max_length=20)),
                ('legal_id', models.CharField(blank=True, default='', max_length=50)),
                ('document_expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('MERCHANT', 'Merchant')], default='CUSTOMER', max_length=10)),
                ('contract_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('rib', models.CharField(blank=True, max_length=30, null=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('level', models.CharField(default='000', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=10)),
                ('product_id', models.CharField(default='000', max_length=10)),
                ('product_type_id', models.CharField(default='000', max_length=10)),
                ('product_name', models.CharField(default='CDP BASIC', max_length=50)),
                ('product_type_name', models.CharField(default='PARTICULIER', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('business_address', models.CharField(blank=True, default='', max_length=255)),
                ('merchant_category', models.CharField(blank=True, default='', max_length=100)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50)),
                ('commercial_registration', models.CharField(blank=True, default='', max_length=50)),
                ('company_registration_id', models.CharField(blank=True, default='', max_length=50)),
                ('trade_license', models.CharField(blank=True, default='', max_length=50)),
                ('activity_sector', models.CharField(blank=True, default='', max_length=100)),
                ('activity_type', models.CharField(blank=True, default='', max_length=100)),
                ('legal_structure', models.CharField(blank=True, default='', max_length=50)),
                ('job_position', models.CharField(blank=True, default='', max_length=100)),
                ('landline_number', models.CharField(blank=True, max_length=20, null=True)),
                ('professional_tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('registration_center', models.CharField(blank=True, default='', max_length=100)),
                ('registry_registration_number', models.CharField(blank=True, default='', max_length=50)),
                ('institution_id', models.CharField(default='0001', max_length=10)),
                ('agence_id', models.CharField(default='211', max_length=10)),
                ('distributeur_id', models.CharField(default='000104', max_length=10)),
                ('channel_id', models.CharField(default='P', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('W2W', 'Wallet to Wallet'), ('W2M', 'Wallet to Merchant'), ('M2M', 'Merchant to Merchant'), ('M2W', 'Merchant to Wallet'), ('TRANSFER', 'Bank Transfer'), ('ATM', 'ATM Withdrawal'), ('QR', 'QR Code Payment')], max_length=10)),
                ('status', models.CharField(choices=[('SIMULATED', 'Simulated'), ('OTP_SENT', 'OTP Sent'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SIMULATED', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=5)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('token', models.CharField(blank=True, db_index=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('source_phone', models.CharField(blank=True, max_length=20)),
                ('source_contract_id', models.CharField(blank=True, max_length=50)),
                ('destination_phone', models.CharField(blank=True, max_length=20)),
                ('destination_rib', models.CharField(blank=True, max_length=30)),
                ('beneficiary_first_name', models.CharField(blank=True, max_length=100)),
                ('beneficiary_last_name', models.CharField(blank=True, max_length=100)),
                ('client_note', models.CharField(blank=True, max_length=255)),
                ('otp', models.CharField(blank=True, max_length=10)),
                ('qr_code', models.CharField(blank=True, max_length=100)),
                ('mcc', models.CharField(blank=True, max_length=10)),
                ('amount_input_mode', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='wallet.wallet')),
                ('source_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
